all: clusterization retrieve_size

clusterization: main.cpp clusterization.cpp
	g++ -o clusterization main.cpp clusterization.cpp -I . -std=c++11

retrieve_size: retrieve_size.cpp
	g++ -o retrieve_size retrieve_size.cpp -I . -std=c++11
